<!-- Generated by vuejs gem ~> github.com/ytbryan/vuejs -->

<template>
  <div id="app">
    <p>{{ message }}</p>
    <button @click="click">toggle</button>
  </div>
</template>

<script>
export default {
  data: function () {
    return {
      message: "Hello <%= name %>!"
    }
  }, 
  watch: {
    onCreated: function(response){
      this.items = response.data
    }
  },
  methods: {
    click: function(response){
      console.log("clicked")
    }
  }, 
  computed: {

  },
  // asyncComputed: {},
  // components: {},
  // mixins: [], 
  // props: {},
  // directives: {}, 
  // filters: {},
}
</script>

<style scoped>
p {
  font-size: 2em;
  text-align: center;
}
</style>
