// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// This is required to support Pug in Vue on Rails.  

module.exports = {  
  test: /\.pug$/,
  oneOf: [
    {
      resourceQuery: /^\?vue/,
      use: ['pug-plain-loader']
    },
    {
      use: ['raw-loader', 'pug-plain-loader']
    }
  ]
}
