// Generated by Vuejs gem ~> github.com/ytbryan/vuejs

export default {
  data: function() {
    return {
      message: "Hello <%= name %>!",
      items: []
    };
  },
  watch: {
    onCreated: function(response){
      this.items = response.data
    }
  },
  methods: {
    onClick: function(response){
      alert("clicked")
      console.log("clicked")
    }
  }, 
  computed: {
  },
  // asyncComputed: {},
  // components: {},
  // mixins: [], 
  // props: {},
  // directives: {}, 
  // filters: {},
};
