// Generated by Vue on Rails gem ~> github.com/ytbryan/vueonrails
// To generate another of this component part, 
// Please run `rails generate vue something` 

export default {
  // props: {},
  data: function() {
    return {
      message: "Hello <%= name %>!",
      items: []
    };
  },
  watch: {
    onCreated: function(response){
      this.items = response.data
    }
  },
  methods: {
    //uncomment the <button  @click="onClick"> at your <%= name %>.vue 
    onClick: function(){
      console.log("clicked")
    }
  }, 
  computed: {
  },
  // components: {},
  // mixins: [], 
  // directives: {}, 
  // filters: {},
  // asyncComputed: {}, // yarn add vue-async-computed
};
