<!-- Generated by Vue on Rails gem ~> github.com/ytbryan/vueonrails -->
<!-- To generate another of this component part, 
Please run `rails generate vue something --seperate` -->

<template>
  <div id="<%= name %>">
    <p>{{ message }}</p>
    <!-- <button @click="onClick">click this</button> -->
  </div>
</template>

<script src="./<%= name %>.js"></script>
<style scoped src="./<%= name %>.css"></style>
