<!-- Generated by Vue on Rails http://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/<%= name %>.js -->
<!-- Generate a component part with separation of concern by running command `rails generate vue something --seperate` -->

<template>
  <div id="<%= name %>">
    <p>{{ message }}</p>
  </div>
</template>

<script src="./<%= name %>.js"></script>
<style scoped src="./<%= name %>.css"></style>
