// Generated by Vuejs gem ~> github.com/ytbryan/vuejs

export default {
  // components: {},
  // mixins: [], 
  // props: {},
  data: function() {
    return {
      message: "Hello <%= name %>!"
    };
  },
  watch: {
    onMounted: function(response){
      this.items = response.data
    }
  },
  methods: {
    click: function(response){
      console.log("clicked")
    }
  } 
};
